### ISSUE TITLE
`countryfetch india` gives info about British Indian Ocean Territory

### ISSUE THREAD

**Issue by wojwesoly** [pridont/countryfetch-deno#1]
https://restcountries.com/v3.1/name/India returns info both about the BIOT and India. BIOT is first so I assume that's why it takes this info. 

Adding `?fullText=true` [seems to resolve the issue](https://restcountries.com/v3.1/name/india?fullText=true).

**Comment by wojwesoly** [comment]
Oh wait, you are not using /name.

Maybe you can compare the whole common name (which is "British Indian Ocean Territory" and "India") instead of fuzzy searching, but that removes the option of searching just by the first letters of the country name.

**Comment by wojwesoly** [comment]
Same thing is happening with `countryfetch samoa`, which gives American Samoa.

**Comment by pridont** [comment]
The program looks for the already cached data, it doesn't make API calls for a particular country. I think the issue is that first attempt at exact match doesn't work correctly and it always resorts to fuzzy search. This code block here is probably the culprit:

```ts
  public find(name: string) {
    name = name.toLowerCase();
    // Find exact match first, then fall back to fuzzy match
    const country = this.list.find((c) => {
      const countryName = c.name.common.toLowerCase();
      return countryName === name || countryName.includes(name);
    });

    if (!country) {
      throw `Cannot find country named ${name}`;
    }
    return country;
  }
```
I'll look into fixing it.

**Comment by pridont** [comment]
It should work fine now.
