### ISSUE TITLE
Countryfetch don't start

### ISSUE THREAD

**Issue by sebastien-cupin** [pridont/countryfetch-deno#2]
Hi, 
I test countryfetch with manjaro kde and I have a problem, countryfetch don't start. Problem of path ?

Steps :

Install deno
Follow the instruction
Integrate path

Result :
![Screenshot_20220626_102826](https://user-images.githubusercontent.com/37769339/175806189-b4ea5e60-52b7-41d0-a68c-bae7410751b7.png)

Can you help me ?
Thks

**Comment by pridont** [comment]
does running it manually work?
for example, try: `deno run --allow-all /path/to/countryfetch_directory/main.ts`

If this works, this means that you haven't integrated path correctly.

**Comment by sebastien-cupin** [comment]
Ok, thanks for support.
I try this
![image](https://user-images.githubusercontent.com/37769339/175808795-e4ce9b0e-09a2-4b8f-888b-a45a36d7f87c.png)

**Comment by sebastien-cupin** [comment]
And there is a invisible folder .deno with countryfetch inside in my home directory...

**Comment by pridont** [comment]
I think you should remove the alias altogether (`unalias countryfetch`) and simply re-run install.sh in the countryfetch directory. If countryfetch is already in your .deno directory, this means it has been installed and you don't have to make alias for it. It should detect the command automatically.  You might have followed the alternative installation instructions in the README.md, which is not necessary if you just use install.sh.

**Comment by sebastien-cupin** [comment]
Then I have copy all of the folder in .deno/bin/
After I try /home/seb/.deno/bin/ but there is a new problem with permission 
![Screenshot_20220626_115950](https://user-images.githubusercontent.com/37769339/175809027-d61208d6-80e8-42b9-a382-8cc367b7d049.png)

**Comment by pridont** [comment]
does running it with sudo work?

**Comment by sebastien-cupin** [comment]
I have found that alias is not permantly, if I quit terminal, I reopen it, my alias is disappear. 

> does running it with sudo work?
![image](https://user-images.githubusercontent.com/37769339/175813213-30c03b72-fa8a-41e4-89c6-da29e60f374c.png)

Or
![Screenshot_20220626_140548](https://user-images.githubusercontent.com/37769339/175813283-c2eafce7-f6c1-4014-bc7a-ac0a44a7408a.png)

I'm beginner, sorry...

**Comment by ProudNoob** [comment]
put your alias in your .bashrc (if using bash) or .zshrc (if using zsh) config will make it permanent

**Comment by pridont** [comment]
I updated the installation instructions in readme. Try following it and if it doesn't work, you can open a new issue.
