### ISSUE TITLE
for some resone it was installed in a diffrent directory

### ISSUE THREAD

**Issue by AlreadyUsed78** [pridont/countryfetch-deno#5]
So countryfetch was installed in ~/.deno/bin/countryfetch, so i had to change the alias.

**Comment by pridont** [comment]
This is the default installation path. You can change the directory by passing the --root flag to install.sh (which basically is `deno install` command). [Check deno script installer docs](https://deno.land/manual/tools/script_installer). I don't think I understand what's the issue, could you elaborate a bit more?

**Comment by pridont** [comment]
Making alias should not be necessary if you run install script. I updated readme to make it clearer.
