### ISSUE TITLE
error: Uncaught TypeError: Cannot read properties of undefined (reading 'join')

### ISSUE THREAD

**Issue by ghost** [pridont/countryfetch-deno#6]
I installed it as it says in the `README.md`.

And it  gave me that error:

```ts
error: Uncaught TypeError: Cannot read properties of undefined (reading 'join')
            latlng: country.latlng.join("/"),
                                   ^
    at Countries.print (file:///home/paij0se/countryfetch/src/countries.ts:88:36)
    at App.run (file:///home/paij0se/countryfetch/src/app.ts:34:38)
    at async file:///home/paij0se/countryfetch/index.ts:2:1
```

Note: i was using ssh on a Windows pc connected to a Ubuntu pc, and the previous version worked fine.

**Comment by pridont** [comment]
Check the updated readme:

If you get an error after installing the newer version of the program, such as "cannot read properties of undefined", you might have an outdated cache. Try running `countryfetch sync` to update the cache.

Append `flags` to that command to enable flags ASCII art.
