### ISSUE TITLE
Country flag emoji not showing

### ISSUE THREAD

**Issue by telometto** [pridont/countryfetch-deno#9]
The country emoji flags do not seem to work properly. Am I doing something wrong?

![Screenshot from 2022-08-08 13-45-43](https://user-images.githubusercontent.com/65364211/183410994-bfaa66f5-f08c-4560-a3d5-0e2e87322a17.png)

**Comment by pridont** [comment]
This is a terminal-specific behavior. Some display letters, and some - emojis.
See [this issue](https://github.com/CondensedMilk7/countryfetch/issues/7).
